### ISSUE TITLE
Add data from "Longitudinal Fecal Shedding of SARS-CoV-2, Pepper Mild Mottle Virus, and Human Mitochondrial DNA in COVID-19 Patients."

### ISSUE THREAD

**Issue by tillahoffmann** [shedding-hub/shedding-hub#2]
The [preprint](https://www.medrxiv.org/content/10.1101/2024.04.22.24305845v1) contains fecal shedding data for human mtDNA, PMMoV, and SARS-CoV-2 in fecal samples for 42 inpatients.

**Comment by YWAN446** [comment]
Andrew has the raw data for this.
