### ISSUE TITLE
Data Request for Estimated Viral Load Data from Ct Values for young2020epidemiologic

### ISSUE THREAD

**Issue by WenfeiXiao** [shedding-hub/shedding-hub#48]
This issue is for communication with the authors of the study "Epidemiologic Features and Clinical Course of Patients Infected With SARS-CoV-2 in Singapore" (doi:10.1001/jama.2020.3204) regarding the estimated viral load data derived from Cycle Threshold (Ct) values. The supplementary material is attached.
[jama-323-1488-s001.pdf](https://github.com/user-attachments/files/17264237/jama-323-1488-s001.pdf)

**Comment by YWAN446** [comment]
As discussed, we will use the data from Goyal et al. to back-calculate the standard curve.
